[2024-11-26T14:27:20.151+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_split_google_sheets.upload_to_google_sheets manual__2024-11-26T14:27:14.429249+00:00 [queued]>
[2024-11-26T14:27:20.159+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_split_google_sheets.upload_to_google_sheets manual__2024-11-26T14:27:14.429249+00:00 [queued]>
[2024-11-26T14:27:20.160+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-26T14:27:20.160+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-11-26T14:27:20.161+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-26T14:27:20.171+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): upload_to_google_sheets> on 2024-11-26 14:27:14.429249+00:00
[2024-11-26T14:27:20.178+0000] {standard_task_runner.py:55} INFO - Started process 109 to run task
[2024-11-26T14:27:20.181+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_split_google_sheets', 'upload_to_google_sheets', 'manual__2024-11-26T14:27:14.429249+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/data_processing_dag.py', '--cfg-path', '/tmp/tmp342skju6']
[2024-11-26T14:27:20.183+0000] {standard_task_runner.py:83} INFO - Job 59: Subtask upload_to_google_sheets
[2024-11-26T14:27:20.242+0000] {task_command.py:388} INFO - Running <TaskInstance: data_split_google_sheets.upload_to_google_sheets manual__2024-11-26T14:27:14.429249+00:00 [running]> on host 910f0d532d2b
[2024-11-26T14:27:20.293+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_split_google_sheets
AIRFLOW_CTX_TASK_ID=upload_to_google_sheets
AIRFLOW_CTX_EXECUTION_DATE=2024-11-26T14:27:14.429249+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-26T14:27:14.429249+00:00
[2024-11-26T14:27:25.629+0000] {logging_mixin.py:137} INFO - Błąd podczas zapisu do Google Sheets: Out of range float values are not JSON compliant
[2024-11-26T14:27:25.632+0000] {python.py:177} INFO - Done. Returned value was: None
[2024-11-26T14:27:25.640+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=data_split_google_sheets, task_id=upload_to_google_sheets, execution_date=20241126T142714, start_date=20241126T142720, end_date=20241126T142725
[2024-11-26T14:27:25.686+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-11-26T14:27:25.698+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
